name: Telegram Notifier
description: Sends notifications to Telegram

inputs:
  token:
    description: "Telegram Bot Token"
    required: true
  chat_id:
    description: "Telegram Chat ID"
    required: true
  thread_id:
    description: "Telegram Thread ID (optional)"
    required: false
  message:
    description: "Message to send"
    required: true
  parse_mode:
    description: "Parse mode for message: Markdown, MarkdownV2, or HTML (default: HTML)"
    required: false

runs:
  using: "composite"
  steps:
    - run: |
        # Default parse mode
        [ -z "$PARSE_MODE" ] && PARSE_MODE="HTML"

        # Добавим аргумент thread_id, если он есть
        THREAD_ARG=""
        [ -n "$THREAD_ID" ] && THREAD_ARG="-d message_thread_id=$THREAD_ID"

        # Send message
        curl -s -X POST "https://api.telegram.org/bot$TOKEN/sendMessage" \
          -d chat_id="$CHAT_ID" \
          -d text="$MESSAGE" \
          -d parse_mode="$PARSE_MODE" \
          $THREAD_ARG
      shell: bash
      env:
        TOKEN: ${{ inputs.token }}
        CHAT_ID: ${{ inputs.chat_id }}
        THREAD_ID: ${{ inputs.thread_id }}
        MESSAGE: ${{ inputs.message }}
        PARSE_MODE: ${{ inputs.parse_mode }}