name: Telegram Notifier
description: Sends notifications to Telegram
inputs:
  token:
    description: "Telegram Bot Token"
    required: true
  chat_id:
    description: "Telegram Chat ID"
    required: true
  thread_id:
    description: "Telegram Thread ID (optional)"
    required: false
  message:
    description: "Message to send"
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        escape_underscores() {
          echo "$1" | sed -E 's/(_)/\\\1/g'
        }

        ESCAPED_MESSAGE="$(escape_underscores "${{ inputs.message }}")"

        if [ -n "${{ inputs.thread_id }}" ]; then
          curl -s -X POST https://api.telegram.org/bot${{ inputs.token }}/sendMessage \
            -H "Content-Type: application/x-www-form-urlencoded; charset=utf-8" \
            -d chat_id="${{ inputs.chat_id }}" \
            -d text="$ESCAPED_MESSAGE" \
            -d parse_mode=Markdown \
            -d message_thread_id="${{ inputs.thread_id }}"
        else
          curl -s -X POST https://api.telegram.org/bot${{ inputs.token }}/sendMessage \
            -H "Content-Type: application/x-www-form-urlencoded; charset=utf-8" \
            -d chat_id="${{ inputs.chat_id }}" \
            -d text="$ESCAPED_MESSAGE" \
            -d parse_mode=Markdown
        fi
